# Generated by Django 2.2.7 on 2022-01-23 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_amount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Place',
        ),
    ]
